### ISSUE TITLE
Help to deploy behind Traefik and question about scalability

### ISSUE THREAD

**Issue by pietrogu** [MISP/x_old_misp_docker#143]
Hi,

i'm trying to deploy this docker image of MISP behind Traefik, but with no luck.
Can someone share some sort of guide (and maybe some docker-compose file template) on how to make this work?

Also, can this dockerization be helpful in realizing a scalable MISP solution?

Thank you in advance
Pietro

**Comment by ftoppi** [comment]
Hello,

assuming you have a working Traefik instance, this is how to expose MISP web container on `misp.foobar.com`:

```
services:
  web:
# comment or remove the ports section
#    ports:
#      - "80:80"
#      - "443:443"
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.misp.rule=Host(`misp.foobar.com`)"
      - "traefik.http.routers.misp.service=misp"
      - "traefik.http.routers.misp.tls=true"
      - "traefik.http.routers.misp.tls.certresolver=foobar"
      - "traefik.http.routers.misp.entrypoints=websecure"
      - "traefik.http.services.misp.loadbalancer.server.port=443"
      - "traefik.http.services.misp.loadbalancer.server.scheme=https"
      - "traefik.http.services.misp.loadbalancer.serversTransport=misp"
      - "traefik.http.serversTransports.misp.insecureSkipVerify=true"

networks:
  traefik:
    external: true
```

Your traefik container needs to:
- be connected to a network called `traefik`
- have a certresolver called foobar
- have a tls entrypoint called websecure
