### ISSUE TITLE
Request: Build for Apple Silicon ARM64 (M1 Ultra)

### ISSUE THREAD

**Issue by packet-rat** [MISP/x_old_misp_docker#166]
We need a supported MISP Docker image for Apple Silicon ARM64 (M1 Ultra).
Pretty Please?

**Comment by colincalnan** [comment]
@packet-rat you can modify the `docker-compose.yml` by adding this property to both web: and db: services

`platform: linux/amd64`

So they would look like this

```
services:
  web:
    platform: linux/amd64
    build: web
    ....

  db:
    platform: linux/amd64
    container_name: misp_db
    image: mysql/mysql-server:5.7
    ....
```

That worked for me to get it built and running, but I'm hitting a different error once I run the containers.

`misp_web  | /usr/bin/sed: couldn't open temporary file ./sedn99toR: Permission denied`
