### ISSUE TITLE
MISP behind Traefik

### ISSUE THREAD

**Issue by ghost** [MISP/x_old_misp_docker#52]
Hi,
I'm trying to serve MISP using Traefik as reverse proxy, but I can't seem to get it to work.
When I try to connect to https://test.local/misp I'm redirected to https://test/

This is my docker-compose.yml:
```
version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false


services:
  web:
    build: web
    depends_on:
      - db
    container_name: misp_web
    image: misp:latest
    restart: unless-stopped
    volumes:
      - /dev/urandom:/dev/random
      - ${DATA_DIR}/web:/var/www/MISP
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - MISP_BASEURL=${MISP_BASEURL}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}
    labels:
      - traefik.backend = misp
      - traefik.frontend.rule=Host:test.local;PathPrefixStrip:/misp
      - traefik.docker.network=proxy
      - traefik.port=443
    networks:
      - internal
      - proxy

  db:
    container_name: misp_db
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
```

and this is my .env : 
```
MYSQL_DATABASE=misp
MYSQL_USER=misp
MYSQL_PASSWORD=misp
MYSQL_ROOT_PASSWORD=misp

MISP_ADMIN_EMAIL=admin@admin.test
MISP_ADMIN_PASSPHRASE=admin
MISP_BASEURL=test.local/misp

POSTFIX_RELAY_HOST=relay.fqdn
TIMEZONE=Europe/Rome

DATA_DIR=./data

```

Can someone help me?
